apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weakspotter-production
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      frontend=ghcr.io/weakspotter/weakspotter-frontend:main,
      backend=ghcr.io/weakspotter/weakspotter-backend:main
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/WeakSpotter/WS-Deploy.git
    targetRevision: HEAD
    path: argocd/production
  destination:
    server: https://kubernetes.default.svc
    namespace: weakspotter-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
