apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weakspotter-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weakspotter-role
subjects:
  - kind: ServiceAccount
    name: weakspotter-service-account
