apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weakspotter-production

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: weakspotter-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/weakspotter/weakspotter-frontend:main
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: https://weakspotter.ozeliurs.com/api
  - target:
      kind: Ingress
      name: weakspotter-frontend-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: weakspotter.ozeliurs.com
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - weakspotter.ozeliurs.com
      - op: replace
        path: /spec/tls/0/secretName
        value: weakspotter-frontend-production-tls
