apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weakspotter-common
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      ai-cve-explainer=ghcr.io/weakspotter/ai-cve-explainer:latest
    argocd-image-updater.argoproj.io/ai-cve-explainer.update-strategy: digest
spec:
  project: default
  source:
    repoURL: https://github.com/WeakSpotter/WS-Deploy.git
    targetRevision: HEAD
    path: common
  destination:
    server: https://kubernetes.default.svc
    namespace: weakspotter-common
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
