apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weakspotter-common
  namespace: weakspotter-common
spec:
  project: default
  source:
    repoURL: https://github.com/WeakSpotter/WS-Deploy.git
    targetRevision: HEAD
    path: argocd/openvas
  destination:
    server: https://kubernetes.default.svc
    namespace: weakspotter-common
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
