apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weakspotter-common

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
