apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weakspotter-openvas-pvc
  namespace: weakspotter-common
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
