apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weakspotter-staging
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      frontend=ghcr.io/weakspotter/weakspotter-frontend:develop,
      backend=ghcr.io/weakspotter/weakspotter-backend:develop
    argocd-image-updater.argoproj.io/frontend.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/backend.update-strategy: alphabetical
spec:
  project: default
  source:
    repoURL: https://github.com/WeakSpotter/WS-Deploy.git
    targetRevision: HEAD
    path: argocd/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: weakspotter-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
